<settings>
    <servers>
        <server>
            <id>github-source</id>
            <username>GH_SOURCE_USERNAME</username>
            <password>GH_SOURCE_PAT</password>
        </server>
        <server>
            <id>github-target</id>
            <username>GH_TARGET_USERNAME</username>
            <password>GH_TARGET_PAT</password>
        </server>
        <server>
            <id>github-plugin-source</id>
            <username>GH_SOURCE_USERNAME</username>
            <password>GH_SOURCE_PAT</password>
        </server>
        <server>
            <id>github-plugin-target</id>
            <username>GH_TARGET_USERNAME</username>
            <password>GH_TARGET_PAT</password>
        </server>
    </servers>
    <activeProfiles>
        <activeProfile>default</activeProfile>
    </activeProfiles>
    <profiles>
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>maven-central</id>
                    <url>https://repo.maven.apache.org/maven2/</url>
                </repository>
                <repository>
                    <id>github-source</id>
                    <url>https://maven.pkg.github.com/GH_SOURCE_ORG/GH_SOURCE_REPO</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
                <repository>
                    <id>github-target</id>
                    <url>https://maven.pkg.github.com/GH_TARGET_ORG/GH_TARGET_REPO</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                    <releases><enabled>true</enabled></releases>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>maven-central-plugin</id>
                    <url>https://repo.maven.apache.org/maven2/</url>
                </pluginRepository>
                <pluginRepository>
                    <id>github-plugin-source</id>
                    <url>https://maven.pkg.github.com/GH_SOURCE_ORG/GH_SOURCE_REPO</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </pluginRepository>
                <pluginRepository>
                    <id>github-plugin-target</id>
                    <url>https://maven.pkg.github.com/GH_TARGET_ORG/GH_TARGET_REPO</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
</settings>